### ISSUE TITLE
[Feature Request] Different rooms for same classes | Change default categories

### ISSUE THREAD

**Issue by sTiKyt** [HeliumEdu/platform#373]
Some of my classes have different rooms depending on day, or might be moved to different rooms for some other reasons

Would be nice to specify different rooms for different days or categories

Also removing all categories and adding my own ones every time is time consuming, would be nice to change default for all subjects you add

**Comment by alexdlaird** [comment]
Helium is not under active development, so while we do fix security hot fixes when necessary, we aren't taking feature requests or implementing them. Thank you for your use of the application!
