### ISSUE TITLE
Helium wont let me merge my google calender

### ISSUE THREAD

**Issue by tsims23** [HeliumEdu/platform#374]
I've added a link to my google calendar, but every time I click enable and go back to the calendar tab it says an error has occurred

**Comment by alexdlaird** [comment]
Looks like you just added a link to Google Calendar as the URL. Follow these instructions to get your personal Google Calendar address's feed, and make sure the calendar feed URL you select is "Secret address in iCal format".

https://support.google.com/calendar/answer/37648?hl=en#zippy=%2Cpublic-address%2Csecret-address%2Cget-your-calendar-view-only
