### ISSUE TITLE
Can’t Add Assignments

### ISSUE THREAD

**Issue by Rowan902** [HeliumEdu/platform#653]
Every time I try to add an assignment, it says that there’s an error. I tried refreshing the page, and it’s still not working.

**Comment by alexdlaird** [comment]
Are you still having this issue? If so, please provide the following details:

- Your Helium username
- Details pertaining to the context of the error (for example, if failing to add an assignment, give details about what you're tagging—Course Group, Course, Categories, etc., any details like this will help us troubleshoot)
- A screenshot of the browser with the error happening
- If you're a superuser, open the developer console in your browser and provide any error stacktraces, or response bodies from failed network requests

**Comment by alexdlaird** [comment]
Resubmit using the issue template for bug reports.
