### ISSUE TITLE
Assignment Creation

### ISSUE THREAD

**Issue by rrambo01** [HeliumEdu/platform#662]
There is an issue with creating my assignments for my calendar

**Comment by alexdlaird** [comment]
Are you still having this issue? If so, please provide the following details:

- Your Helium username
- Details pertaining to the context of the error (for example, if failing to add an assignment, give details about what you're tagging—Course Group, Course, Categories, etc., any details like this will help us troubleshoot)
- A screenshot of the browser with the error happening
- If you're a superuser, open the developer console in your browser and provide any error stacktraces, or response bodies from failed network requests
